project:
  type: book

book:
  title: "World of PKMN"
  author: "Deeshura"
  date: "5/16/2025"
  # sidebar options
  sidebar:
    title: " "
    search: true
  # footer
  page-footer:
    center: |
      Written by Deeshura, and rendered with Quarto {{< version >}}.
  # layout
  chapters:
    - index.qmd
    
    - 0_introduction/why.qmd
    
    - 0_introduction/intro.qmd
    
    - part: "Player Characters"
      chapters: 
        - 1_playersCharacters/thePlayer.qmd
        - 1_playersCharacters/characters.qmd
        - 1_playersCharacters/characterCreation.qmd
        - 1_playersCharacters/progression.qmd
        
    - part: "Playing the Game"
      chapters: 
        - 2_playingGame/rolling.qmd
        - 2_playingGame/time.qmd
        - 2_playingGame/turnOrder.qmd
        - 2_playingGame/dungeonCrawling.qmd
        - 2_playingGame/stealth.qmd
        - 2_playingGame/battles.qmd
        - 2_playingGame/resting.qmd
        - 2_playingGame/downtime.qmd
        
    - part: "Moves, Effects, and Conditions"
      chapters: 
        - 3_mEC/usingMoves.qmd
        - 3_mEC/moveAttributes.qmd
        - 3_mEC/moveTags.qmd
        - 3_mEC/statusEffects.qmd
        - 3_mEC/statusConditions.qmd
        
  appendices: 
    - 5_appendix/types.qmd
    
    - part: "Move Lists"
      chapters: 
        - 5_appendix/movesNormal.qmd
        - 5_appendix/movesFighting.qmd
        - 5_appendix/movesFlying.qmd
        - 5_appendix/movesPoison.qmd
        - 5_appendix/movesGround.qmd
        - 5_appendix/movesRock.qmd
        - 5_appendix/movesBug.qmd
        - 5_appendix/movesGhost.qmd
        - 5_appendix/movesSteel.qmd
        - 5_appendix/movesFire.qmd
        - 5_appendix/movesWater.qmd
        - 5_appendix/movesGrass.qmd
        - 5_appendix/movesElectric.qmd
        - 5_appendix/movesPsychic.qmd
        - 5_appendix/movesIce.qmd
        - 5_appendix/movesDragon.qmd
        - 5_appendix/movesDark.qmd
        - 5_appendix/movesFairy.qmd
        
    - part: "Archetypes"
      chapters: 
        - 5_appendix/archetypeArcanist.qmd
        - 5_appendix/archetypeBard.qmd
        - 5_appendix/archetypeHealer.qmd
        - 5_appendix/archetypeKnight.qmd
        - 5_appendix/archetypeRanger.qmd
        - 5_appendix/archetypeScholar.qmd
        - 5_appendix/archetypeThief.qmd
        - 5_appendix/archetypeWarrior.qmd
        
    - 5_appendix/backgrounds.qmd
    - 5_appendix/items.qmd
    - 5_appendix/glossary.qmd
    
    - 5_appendix/debug.qmd
    
bibliography: references.bib

format:
  html:
    # theme
    brand: _brand.yml
  pdf:
    pdf-engine: lualatex
    # class
    documentclass: scrbook
    # fonts
    mainfont: "EB Garamond"
    fontsize: 11pt
    #geometry
    geometry: 
      - paperwidth=148mm
      - paperheight=210mm
      - left=15mm
      - right=15mm
      - top=20mm
      - bottom=25mm
    #header
    include-in-header:
      - text: |
          \usepackage{array}
          \usepackage{caption}
          \usepackage{graphicx}
          \usepackage{siunitx}
          \usepackage[normalem]{ulem}
          \usepackage{colortbl}
          \usepackage{multirow}
          \usepackage{hhline}
          \usepackage{calc}
          \usepackage{tabularx}
          \usepackage{threeparttable}
          \usepackage{wrapfig}
          \usepackage{adjustbox}
          \usepackage{hyperref}